import type { UploadType } from "./types";

export const UPLOAD_TYPES: {
  type: UploadType;
  label: string;
  description: string;
}[] = [
  {
    type: "operations_report",
    label: "Operations Report",
    description: "Sales, service, controls, and FOB data across all stores",
  },
  {
    type: "kiosk",
    label: "Kiosk Report",
    description: "Kiosk sales, guest count, and lobby percentage breakdowns",
  },
  {
    type: "time_slice",
    label: "Time Slice Summary",
    description: "Overnight sales and in-store breakdowns by time window",
  },
  {
    type: "service",
    label: "Service Report (3 Peaks)",
    description: "Peak-hour OEPE, R2P, and KVS times for 3 time windows",
  },
  {
    type: "food_over_base",
    label: "Food Over Base",
    description: "Standalone FOB breakdown: waste, condiment, stat loss",
  },
  {
    type: "comparison_report",
    label: "Voice Comparison Report",
    description: "Voice of the Customer survey results and satisfaction scores",
  },
  {
    type: "shop_tracker",
    label: "Shop Tracker",
    description: "Mystery shop scores for the month",
  },
  {
    type: "bonus_program",
    label: "Bonus Program",
    description: "Bonus criteria tracking: TCPH, FOB, OSAT, PACE, and points",
  },
  {
    type: "pnl",
    label: "Monthly P&L",
    description: "Profit & Loss statement with budget vs actual by line item",
  },
  {
    type: "labor",
    label: "Labor Spreadsheet",
    description: "Hours, TPCH, overtime, PSL, vacation, and labor dollar details",
  },
];

export const MONTH_NAMES = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const MONTH_NAMES_SHORT = [
  "Jan", "Feb", "Mar", "Apr", "May", "Jun",
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
];

export const STORE_NAME_TO_NUMBER: Record<string, string> = {
  "East Henrietta": "1350",
  "Canandaigua": "2368",
  "Penn Yan": "2562",
  "West Henrietta": "3090",
  "Waterloo": "3481",
  "Farmington": "7066",
  "Perinton Square": "10413",
  "Marketplace": "11172",
  "Ovid": "25738",
  "Winton": "32511",
  "Winton Rd": "32511",
  "South Winton": "32511",
  "Geneva": "33555",
  "Victor": "34940",
  "Manchester": "18842",
};

// Metric metadata for variance color-coding
// "higher_is_better" = true means green when current > prior
// "higher_is_better" = false means green when current < prior (e.g., times, costs)
export type VarianceDirection = "higher_is_better" | "lower_is_better" | "neutral";

export const METRIC_DIRECTIONS: Record<string, VarianceDirection> = {
  // Sales - higher is better
  all_net_sales: "higher_is_better",
  product_sales: "higher_is_better",
  avg_check: "higher_is_better",
  tcc: "higher_is_better",
  breakfast_sales: "higher_is_better",
  breakfast_tcc: "higher_is_better",
  breakfast_pct_of_sales: "higher_is_better",
  breakfast_avg_check: "higher_is_better",
  dt_sales: "higher_is_better",
  dt_tcc: "higher_is_better",
  dt_avg_check: "higher_is_better",
  dt_pct_of_sales: "higher_is_better",
  mcdelivery_sales: "higher_is_better",
  mcdelivery_tcc: "higher_is_better",
  mcdelivery_avg_check: "higher_is_better",
  mcdelivery_pct_of_sales: "higher_is_better",
  mobile_order_sales: "higher_is_better",
  mobile_order_tcc: "higher_is_better",
  mobile_order_avg_check: "higher_is_better",
  mobile_order_pct_of_sales: "higher_is_better",
  kiosk_sales: "higher_is_better",
  kiosk_tcc: "higher_is_better",
  kiosk_avg_check: "higher_is_better",
  kiosk_pct_of_lobby_sales: "higher_is_better",
  kiosk_pct_of_lobby_tcc: "higher_is_better",
  overnight_sales: "higher_is_better",
  in_store_sales: "higher_is_better",
  in_store_tcc: "higher_is_better",
  in_store_pct_of_sales: "neutral",

  // Speed of Service - lower is better
  kvs_daily_avg: "lower_is_better",
  r2p_daily_avg: "lower_is_better",
  dt_oepe_daily_avg: "lower_is_better",
  dt_ttl_avg: "lower_is_better",
  dt_oepe_peak_avg: "lower_is_better",
  r2p_peak_avg: "lower_is_better",
  kvs_peak_avg: "lower_is_better",
  dt_oepe_peak_7a9a: "lower_is_better",
  r2p_peak_7a9a: "lower_is_better",
  kvs_peak_7a9a: "lower_is_better",
  dt_oepe_peak_11a2p: "lower_is_better",
  r2p_peak_11a2p: "lower_is_better",
  kvs_peak_11a2p: "lower_is_better",
  dt_oepe_peak_5p7p: "lower_is_better",
  r2p_peak_5p7p: "lower_is_better",
  kvs_peak_5p7p: "lower_is_better",

  // Food Cost - lower is better
  food_base_pct: "lower_is_better",
  completed_waste_pct: "lower_is_better",
  raw_waste_pct: "lower_is_better",
  stat_loss_pct: "lower_is_better",
  condiment_pct: "lower_is_better",
  unexplained_pct: "lower_is_better",
  food_over_base_pct: "lower_is_better",
  food_cost_actual_pct: "lower_is_better",
  paper_cost_actual_pct: "lower_is_better",

  // Voice - higher is better (except problem/b2b)
  voice_overall_satisfaction: "higher_is_better",
  voice_accuracy: "higher_is_better",
  voice_quality: "higher_is_better",
  voice_be_fast: "higher_is_better",
  voice_dt_satisfaction: "higher_is_better",
  voice_dt_b2b: "lower_is_better",
  voice_instore_satisfaction: "higher_is_better",
  voice_instore_b2b: "lower_is_better",
  voice_experienced_problem: "lower_is_better",
  voice_friendliness: "higher_is_better",
  voice_be_clean: "higher_is_better",
  voice_survey_count: "higher_is_better",

  // Shop - higher is better
  shop_score_1: "higher_is_better",
  shop_score_2: "higher_is_better",
  shop_avg: "higher_is_better",

  // P&L costs - lower is better, PACE higher is better
  total_labor_actual_pct: "lower_is_better",
  payroll_tax_actual_pct: "lower_is_better",
  advertising_actual_pct: "lower_is_better",
  promotion_actual_pct: "lower_is_better",
  outside_service_actual_pct: "lower_is_better",
  linen_actual_pct: "lower_is_better",
  op_supply_actual_pct: "lower_is_better",
  mr_actual_pct: "lower_is_better",
  utilities_actual_pct: "lower_is_better",
  office_actual_pct: "lower_is_better",
  pace_actual_pct: "higher_is_better",

  // Labor
  tpch: "higher_is_better",
  sales_per_labor_hour: "higher_is_better",
  overtime_hours_actual: "lower_is_better",
  total_labor_dollars: "lower_is_better",
  avg_hourly_wage: "neutral",
};

// Format types for display
export type MetricFormat = "currency" | "percent" | "number" | "time_sec" | "boolean";

export const METRIC_FORMATS: Record<string, MetricFormat> = {
  // Currency
  all_net_sales: "currency",
  product_sales: "currency",
  breakfast_sales: "currency",
  dt_sales: "currency",
  mcdelivery_sales: "currency",
  mobile_order_sales: "currency",
  kiosk_sales: "currency",
  overnight_sales: "currency",
  in_store_sales: "currency",
  psl_dollars: "currency",
  crew_vacation_dollars: "currency",
  mgmt_vacation_dollars: "currency",
  crew_dollars: "currency",
  total_labor_dollars: "currency",
  labor_diff_dollars: "currency",
  avg_hourly_wage: "currency",
  avg_check: "currency",
  breakfast_avg_check: "currency",
  dt_avg_check: "currency",
  mcdelivery_avg_check: "currency",
  mobile_order_avg_check: "currency",
  kiosk_avg_check: "currency",

  // Percent
  breakfast_pct_of_sales: "percent",
  dt_pct_of_sales: "percent",
  mcdelivery_pct_of_sales: "percent",
  mobile_order_pct_of_sales: "percent",
  kiosk_pct_of_lobby_sales: "percent",
  kiosk_pct_of_lobby_tcc: "percent",
  in_store_pct_of_sales: "percent",
  food_base_pct: "percent",
  completed_waste_pct: "percent",
  raw_waste_pct: "percent",
  stat_loss_pct: "percent",
  condiment_pct: "percent",
  unexplained_pct: "percent",
  food_over_base_pct: "percent",
  food_cost_actual_pct: "percent",
  food_cost_goal_pct: "percent",
  paper_cost_actual_pct: "percent",
  paper_cost_goal_pct: "percent",
  total_labor_actual_pct: "percent",
  total_labor_goal_pct: "percent",
  payroll_tax_actual_pct: "percent",
  payroll_tax_goal_pct: "percent",
  advertising_actual_pct: "percent",
  advertising_goal_pct: "percent",
  promotion_actual_pct: "percent",
  promotion_goal_pct: "percent",
  outside_service_actual_pct: "percent",
  outside_service_goal_pct: "percent",
  linen_actual_pct: "percent",
  linen_goal_pct: "percent",
  op_supply_actual_pct: "percent",
  op_supply_goal_pct: "percent",
  mr_actual_pct: "percent",
  mr_goal_pct: "percent",
  utilities_actual_pct: "percent",
  utilities_goal_pct: "percent",
  office_actual_pct: "percent",
  office_goal_pct: "percent",
  pace_actual_pct: "percent",
  non_product_actual_pct: "percent",
  non_product_goal_pct: "percent",
  cash_variance_actual_pct: "percent",
  cash_variance_goal_pct: "percent",
  labor_diff_pct: "percent",
  psl_pct_of_sales: "percent",
  voice_overall_satisfaction: "percent",
  voice_accuracy: "percent",
  voice_quality: "percent",
  voice_be_fast: "percent",
  voice_dt_satisfaction: "percent",
  voice_dt_b2b: "percent",
  voice_instore_satisfaction: "percent",
  voice_instore_b2b: "percent",
  voice_experienced_problem: "percent",
  voice_friendliness: "percent",
  voice_be_clean: "percent",
  bonus_pace_goal_pct: "percent",
  bonus_pace_actual_pct: "percent",
  bonus_pace_adj_pct: "percent",

  // Time (seconds)
  kvs_daily_avg: "time_sec",
  r2p_daily_avg: "time_sec",
  dt_oepe_daily_avg: "time_sec",
  dt_ttl_avg: "time_sec",
  dt_oepe_peak_avg: "time_sec",
  r2p_peak_avg: "time_sec",
  kvs_peak_avg: "time_sec",
  dt_oepe_peak_7a9a: "time_sec",
  r2p_peak_7a9a: "time_sec",
  kvs_peak_7a9a: "time_sec",
  dt_oepe_peak_11a2p: "time_sec",
  r2p_peak_11a2p: "time_sec",
  kvs_peak_11a2p: "time_sec",
  dt_oepe_peak_5p7p: "time_sec",
  r2p_peak_5p7p: "time_sec",
  kvs_peak_5p7p: "time_sec",

  // Booleans
  bonus_greens_fees_met: "boolean",
  bonus_tcph_goal_met: "boolean",
  bonus_food_cost_goal_met: "boolean",
  bonus_osat_goal_met: "boolean",
  bonus_complaints_goal_met: "boolean",
  bonus_crew_trainers_goal_met: "boolean",
  bonus_pace_goal_met: "boolean",
};
